#!/usr/bin/python3

# This file is part of Project Babel.
# Copyright 2021 Graham Shaw
# Redistribution and modification are permitted within the terms of the
# BSD-3-Clause licence as defined by v3.4 of the SPDX Licence List.

import os
import re
import json

def make_path(textid):
    path = 'raw'
    if textid >= 10000:
        path += '/%d' % (textid // 10000)
    if textid >= 1000:
        path += '/%d' % ((textid // 1000) % 10)
    if textid >= 100:
        path += '/%d' % ((textid // 100) % 10)
    path += '/%d' % ((textid // 10) % 10)
    path += '/%d' % textid
    path += '/%d-h' % textid
    return path

files = {}
for root, dirnames, filenames in os.walk('raw'):
    for filename in filenames:
        m = re.match('^([0-9]+)-h.html?$', filename)
        if m:
            textid = int(m.group(1))
            if root == make_path(textid):
                pathname = os.path.join(root, filename)
                files[textid] = pathname

print(json.dumps(files))
